name: setup commons
on: workflow_dispatch
defaults:
  run:
    shell: bash

jobs:
  common-setup-default:
    runs-on: ubuntu-20.04
    steps:
      - name: <Setup> Prepare the repository / Python Runtime / Python Dependencies
        id: setup-common
        uses: ./github/actions/common_setup
      - name: <Deploy> Print outputs
        run: |
          echo ${{ steps.setup-common.outputs.python-version }}
          pip list

  common-setup-no-python:
    runs-on: ubuntu-20.04
    steps:
      - name: <Setup> Prepare the repository / Python Runtime / Python Dependencies
        id: setup-common
        uses: ./github/actions/common_setup
        with:
          python: false
      - name: <Deploy> Print outputs
        run: |
          echo ${{ steps.setup-common.outputs.python-version }}
          pip list

  common-setup-no-python:
    runs-on: ubuntu-20.04
    steps:
      - name: <Setup> Prepare the repository / Python Runtime / Python Dependencies
        id: setup-common
        uses: ./github/actions/common_setup
        with:
          python: false
      - name: <Deploy> Print outputs
        run: |
          echo ${{ steps.setup-common.outputs.python-version }}
          pip list

  common-setup-dev-dependency:
    runs-on: ubuntu-20.04
    steps:
      - name: <Setup> Prepare the repository / Python Runtime / Python Dependencies
        id: setup-common
        uses: ./github/actions/common_setup
        with:
          requirements-suffix: "-dev"
      - name: <Deploy> Print outputs
        run: |
          echo ${{ steps.setup-common.outputs.python-version }}
          pip list
