name: manual output
on:
  workflow_dispatch:
    outputs:
      output1:
        value: ${{ jobs.write-out-1.outputs.output1 }}
      output2:
        value: ${{ jobs.write-out-1.outputs.output2 }}
      output3:
        value: ${{ jobs.write-out-2.outputs.output3 }}
      output4:
        value: ${{ jobs.write-out-2.outputs.output4 }}

jobs:
  write-out-1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  write-out-2:
    runs-on: ubuntu-latest
    outputs:
      output3: ${{ steps.step3.outputs.test }}
      output4: ${{ steps.step4.outputs.test }}
    steps:
      - id: step3
        run: echo "test=helloW" >> "$GITHUB_OUTPUT"
      - id: step4
        run: echo "test=worldW" >> "$GITHUB_OUTPUT"